# Generated by Django 5.2.6 on 2025-10-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Image')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Texte du bouton')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='Lien du bouton')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Bannière',
                'verbose_name_plural': 'Bannières',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SteveShop', max_length=100, verbose_name='Nom du site')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='Livraison gratuite à partir de')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Frais de livraison')),
            ],
            options={
                'verbose_name': 'Configuration du Site',
                'verbose_name_plural': 'Configuration du Site',
            },
        ),
    ]
