# Generated by Django 5.2.6 on 2025-10-07 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='nom ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('address', models.CharField(max_length=255, verbose_name='adresse')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('postal_code', models.CharField(max_length=20, verbose_name='code postal')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant total')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='frais de livraison')),
                ('status', models.CharField(choices=[('PENDING', 'en attente'), ('PAID', 'payée'), ('PROCESSING', 'en cours de traitement'), ('SHIPPED', 'expédiée'), ('DELIVERED', 'livrée'), ('CANCELLED', 'annulée')], default='PENDING', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'article de commande',
                'verbose_name_plural': 'articles de commande',
            },
        ),
    ]
